using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations.Application;

/// <inheritdoc />
public partial class AddTicketReference : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // Written out rather than left to the scaffolded AddColumn, which attaches the
        // identity in the same step that adds the column. Every existing row then takes
        // the column default, so the unique index below cannot be created - and where it
        // can, the backlog is numbered in physical order rather than the order it was
        // raised in.
        //
        // So: add it plain, number the backlog oldest-first, then hand the counter over.
        migrationBuilder.Sql("""
            ALTER TABLE ticket.tickets ADD COLUMN reference integer;

            UPDATE ticket.tickets AS t
            SET reference = numbered.position
            FROM (
                SELECT id, row_number() OVER (ORDER BY created_at, id) AS position
                FROM ticket.tickets
            ) AS numbered
            WHERE t.id = numbered.id;

            ALTER TABLE ticket.tickets
                ALTER COLUMN reference SET NOT NULL,
                ALTER COLUMN reference ADD GENERATED BY DEFAULT AS IDENTITY;

            -- The sequence starts at 1 whatever the backlog holds, so it has to be moved
            -- past the highest reference already handed out or the next insert collides.
            SELECT setval(
                pg_get_serial_sequence('ticket.tickets', 'reference'),
                COALESCE((SELECT MAX(reference) FROM ticket.tickets), 0) + 1,
                false);
            """);

        migrationBuilder.CreateIndex(
            name: "ix_tickets_reference",
            schema: "ticket",
            table: "tickets",
            column: "reference",
            unique: true);
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropIndex(
            name: "ix_tickets_reference",
            schema: "ticket",
            table: "tickets");

        migrationBuilder.DropColumn(
            name: "reference",
            schema: "ticket",
            table: "tickets");
    }
}
